### ISSUE TITLE
Generation of a new version in npm?

### ISSUE THREAD

**Issue by lpetit-yseop** [Mogztter/antora-lunr#10]
Hello, 

we are interested in what is new in the master branch, especially the fact that it is possible to have an empty URL in the playbook, and that it will then create relative URLs: https://github.com/Mogztter/antora-lunr/blob/master/lib/generate-index.js#L23

Indeed, we find it to be a very interesting purpose to have a website that can be hosted at several URLs (for testing, for UAT, for prod), without having to create separate bundles for each environment.

Do you think the project is in a stable enough state that a new version could be produced and released to npm?

**Comment by Mogztter** [comment]
Hello @lpetit-yseop,

No worries, I will publish a new version tomorrow 😉

**Comment by Mogztter** [comment]
And it's done: https://www.npmjs.com/package/antora-lunr

**Comment by lpetit-yseop** [comment]
> And it's done: https://www.npmjs.com/package/antora-lunr

Thanks, you rock!
