### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by Adito5393** [Mogztter/antora-lunr#100]
Thanks for sharing this awesome tool!

Is there any docker image based on your [antora-site-generator-lunr](https://github.com/Mogztter/antora-site-generator-lunr)?
That would run exactly as [the antora/antora](https://gitlab.com/antora/docker-antora/-/tree/master) image? 

PS: I have only found this thread on [gitter.im](https://gitter.im/antora/users?at=5eb2aa7e347bd616305aa782) regarding the topic.

**Comment by Adito5393** [comment]
Would you be interested in PR with a dockerfile + github action to automatically push image to Docker Hub triggered by the release event in github? 

I am thinking the PR would be better done to the antora-site-generator-lunr repo. Because the dockerfile will make use of that new node package. What do you think? 

You will have to manually set the secret credentials for your docker hub account.

**Comment by Mogztter** [comment]
> Would you be interested in PR with a dockerfile + github action to automatically push image to Docker Hub triggered by the release event in github?

We could start by documenting how to extend the official base image `antora/antora` in order to use Antora Lunr.


> I am thinking the PR would be better done to the antora-site-generator-lunr repo.

Yes, we should document it in the `antora-site-generator-lunr` repository (and probably add a link in here).

**Comment by Adito5393** [comment]
Alright, the PR will contain an update to the `README.md` file also. I have a working docker image and it was easy enough just following the [Antora guidelines](https://gitlab.com/antora/docker-antora/-/tree/master#extend-image). The final `Dockerfile` is only this:

```dockerfile
FROM antora/antora:2.3.4

ENV DOCSEARCH_ENABLED=true \
    DOCSEARCH_ENGINE=lunr

RUN yarn global add antora-site-generator-lunr 
```

The output of building the docker image: `docker build -t antora-lunr-search:0.5.0 -t antora-lunr-search:latest .` was:

```bash
Sending build context to Docker daemon  525.8kB
Step 1/3 : FROM antora/antora:2.3.4
 ---> 137a5b66917b
Step 2/3 : ENV DOCSEARCH_ENABLED=true     DOCSEARCH_ENGINE=lunr
 ---> Running in b819ac0f7c85
Removing intermediate container b819ac0f7c85
 ---> 566f2aa78ef8
Step 3/3 : RUN yarn global add antora-site-generator-lunr
 ---> Running in 8972043a2d24
yarn global v1.22.4
[1/4] Resolving packages...
warning antora-site-generator-lunr > antora-lunr > cheerio > cheerio-select-tmp@0.1.1: Use cheerio-select instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "antora-site-generator-lunr@0.5.0" has no binaries
Done in 7.41s.
Removing intermediate container 8972043a2d24
 ---> 4ba2c31cec04
Successfully built 4ba2c31cec04
Successfully tagged antora-lunr-search:0.5.0
Successfully tagged antora-lunr-search:latest
```

I could even overwrite the CMD entry point such that instead of the default `antora` command it can be: `antora --generator antora-site-generator-lunr`. This would mean less arguments to be added when calling docker run! But also less transparent and the final user will not be able to use this image to run the default `antora-site-generator` (this should not be a problem, because he can use the official antora image for the default generator).

What do you think? 

I personally would like to have the `antora --generator antora-site-generator-lunr` set by default, but willing to compromise on this one 😃

**Comment by Adito5393** [comment]
Maybe the DockerHub image name should contain the antora version also. I propose to name it `antora-v2.3.4-lunr:0.5.0` with the tag only pointing to your versioning scheme.

What do you think?

**Comment by Adito5393** [comment]
Support for Docker was added.
