### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by yangxuan74** [Mogztter/antora-lunr#117]
Does Lunr support Chinese search? If not, how can I make it support?

**Comment by Mogztter** [comment]
Hello @yangxuan74 

We are using https://github.com/MihaiValentin/lunr-languages to provide support for other languages. Unfortunately, `lunr-languages` does not support Chinese but you can contribute a new language: https://github.com/MihaiValentin/lunr-languages/blob/master/CONTRIBUTING.md

**Comment by yangxuan74** [comment]
I found lunr that supports Chinese https://github.com/darkyzhou/lunr-languages-zh, but how does it add toantora-site-generator-lunr?

**Comment by Mogztter** [comment]
Unfortunately, `darkyzhou/lunr-languages-zh` is a complete fork of `lunr-languages` so I'm a bit unsure... 

I guess it would be nice if each language was distributed as a standalone npm package. Then, we could implement a logic to load additional/optional languages.

@darkyzhou What do you think about this idea?

**Comment by darkyzhou** [comment]
> Unfortunately, `darkyzhou/lunr-languages-zh` is a complete fork of `lunr-languages` so I'm a bit unsure...
> 
> I guess it would be nice if each language was distributed as a standalone npm package. Then, we could implement a logic to load additional/optional languages.
> 
> @darkyzhou What do you think about this idea?

I think it's a nice idea. :)

Since the authors of both lunr-languages and `lunr.zh.js` are still inactive on GitHub. One can just copy `lunr.zh.js`'s content from the [PR](https://github.com/MihaiValentin/lunr-languages/pull/53) and publish it as an individual npm package.

**Comment by darkyzhou** [comment]
holy moly, MihaiValentin is back and that PR is merged.

now lunr-languages v1.5.0 natively supports Chinese!

@Mogztter @yangxuan74

**Comment by yangxuan74** [comment]
Thank you for bringing this to my attention.That's good news.

**Comment by Mogztter** [comment]
> holy moly, MihaiValentin is back and that PR is merged.
now lunr-languages v1.5.0 natively supports Chinese!

Awesome news!

> Thank you for bringing this to my attention.That's good news.

👍🏻 
Feel free to submit a pull request to upgrade to the latest version https://github.com/MihaiValentin/lunr-languages/releases/tag/1.7.0
