### ISSUE TITLE
Readme update: Building site on Windows

### ISSUE THREAD

**Issue by djwfyi** [Mogztter/antora-lunr#126]
For anyone building on Windows like me, can we add a sidebar or the like noting the following:

# Terminal / Command Prompt / PowerShell

To use PowerShell, the user needs to change the execution policy (as an Administrator) with

```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
```

Alternatively, use `cmd.exe`.

# Setting Environment Variables 

Environment variables must be set apart from the `antora` call. As so:

```
C:\docs>set DOCSEARCH_ENABLED=true
C:\docs>set DOCSEARCH_ENGINE=lunr
C:\docs>antora antora-playbook.yml
```

**Comment by Mogztter** [comment]
Hey @dwhitelf 

Sure, it's a good idea, would you like to submit a pull request to add all these information? I guess we could add a `NOTE` block in the "Generate the site" section: https://github.com/Mogztter/antora-lunr#generate-the-site

What do you think?

**Comment by ggrossetie** [comment]
Development continues on https://gitlab.com/antora/antora-lunr-extension/
