### ISSUE TITLE
Search URLs ignoring site.url?

### ISSUE THREAD

**Issue by triamond7** [Mogztter/antora-lunr#13]
Is it possible that the generated search URLs are ignoring the Antora site.yml file's site.url setting? I'm getting only relative URLs generated no matter what I have site.url set to.

Thanks for this great project, BTW, and for the recent update.

**Comment by Mogztter** [comment]
I would say no... the `site.url` is indexed in:

https://github.com/Mogztter/antora-lunr/blob/b46ec8b92490d3c5cb838216a4360f7bc6a4325e/lib/generate-index.js#L74

And used in the result list:

https://github.com/Mogztter/antora-lunr/blob/b46ec8b92490d3c5cb838216a4360f7bc6a4325e/supplemental_ui/js/vendor/search.js#L167-L176

Could you please provide more details ? Maybe a sample `site.yml` with the current and expected URL ?

**Comment by triamond7** [comment]
Thanks for the quick response.

I solved this. No problem with antora-lunr; I was referring in a shell script to an older generator.js (from eskwayrd's project, slightly modified). I got rid of the reference, and the index URLs are building properly. All good.

**Comment by Mogztter** [comment]
Good, thanks for the follow-up. Can we close this issue ?

**Comment by triamond7** [comment]
Yes, definitely. Sorry for the false alarm.

**Comment by Mogztter** [comment]
No worries 😀
