### ISSUE TITLE
Provide this library as an Antora 3 pipeline extension

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/antora-lunr#131]
Currently, this library is available as a custom site generator (through https://github.com/Mogztter/antora-site-generator-lunr).

With the introduction of the pipeline extension feature in Antora 3, we can simplify the integration.
The pipeline extension provides a lightweight event-based system that we can leverage to generate a search index.

I think we should register our extension on `beforePublish`:

```js
module.exports.register = (pipeline, { config }) => {
  pipeline
    .on('beforePublish', ({ playbook, contentCatalog }) => {
      // generate a search index
    })
}
```

Additionally, extensions can be configured: https://docs.antora.org/antora/3.0/extend/pipeline/configure-extension/ so we could potentially address the following issues:

- https://github.com/Mogztter/antora-lunr/issues/33
- https://github.com/Mogztter/antora-lunr/issues/75

**Comment by mojavelinux** [comment]
I'm excited to see this happening. Before this is merged in, I'd like you to consider my invitation to graduate this project to the Antora organization on GitLab and making it an official extension of the Antora project. If you decide to accept that invitation, I'd like to suggest that we only merge this change in to that instance instead of this one, thus making a clean break between the old and the new.

**Comment by mojavelinux** [comment]
I'm ready to graduate the project at any time, though I'd like to bring it in as an extension only (perhaps with a new name). (We can still keep the history).

**Comment by Mogztter** [comment]
> If you decide to accept that invitation, I'd like to suggest that we only merge this change in to that instance instead of this one, thus making a clean break between the old and the new.

That's a good idea. I was actually thinking about how we will manage the transition.
That should indeed make it clear that `antora/lunr-extension` is the new extension (based on the pipeline feature).

> I'm ready to graduate the project at any time, though I'd like to bring it in as an extension only (perhaps with a new name). (We can still keep the history).

Let me know when the repository/project is ready on GitLab 😀

**Comment by mojavelinux** [comment]
@Mogztter How do you feel about the repository name `antora-lunr-extension` and the package name `@antora/lunr-extension`?

Or would you prefer something like antora-lunr-integration?

I definitely think "lunr" instead of "lunrjs" is the right choice since the lunr package is without the "js" part.

**Comment by Mogztter** [comment]
> How do you feel about the repository name antora-lunr-extension and the package name @antora/lunr-extension?

Perfect.

> Or would you prefer something like antora-lunr-integration?

No extension is better as it refers to the pipeline extension (and sounds better).

> I definitely think "lunr" instead of "lunrjs" is the right choice since the lunr package is without the "js" part.

I agree 👍🏻

**Comment by mojavelinux** [comment]
@Mogztter I have set up the new repository. https://gitlab.com/antora/antora-lunr-extension

I could have attempted to import the repository from GitHub, but since the project is being restructured, I figured that might just complicate things. Try to integrate the extension-based branch into the main branch and see how it goes. If something goes sideways, we can start over.

**Comment by Mogztter** [comment]
Fixed in https://github.com/Mogztter/antora-lunr/commit/618c1260a3d5c8d962f17c12e407f900021d894e

Please note that future development will happen on GitLab. This repository will be archived and marked as read-only.

We should probably update the README to explain:

- why the repository is marked as read-only
- where users can find the latest version (compatible with Antora 3+)
- that the extension is now an "official" extension for Antora

@thor if you would like to submit a pull request for that, I would be more than happy to review it 🤗
