### ISSUE TITLE
Remove header from generate-index

### ISSUE THREAD

**Issue by abrezemljak** [Mogztter/antora-lunr#135]
Hello,

I would like to remove h6 titles from lunr generated search-index. Is that in any way possible? I've tweaked the generate-index.js and removed the h6 entry from the following line (line 64):
`$('h2,h3,h4,h5', article).each(function () {` but that doesn't seem to work. 

Any suggestions.

**Comment by ggrossetie** [comment]
Development continues on https://gitlab.com/antora/antora-lunr-extension/
