### ISSUE TITLE
Allow pages to be excluded from indexing

### ISSUE THREAD

**Issue by mojavelinux** [Mogztter/antora-lunr#15]
The indexer should skip pages which are marked as "noindex". For example, consider a page which has the following meta tag:

```html
<meta name="robots" content="noindex">
```

Another option is to honor exclusions in robot.txt (or perhaps it should be both).

Here's what Google has to say about noindex: https://support.google.com/webmasters/answer/93710?hl=en

Here are some other ideas around inclusion/exclusion to consider: https://swiftype.com/documentation/site-search/crawler-configuration/content-inclusion-exclusion

**Comment by Mogztter** [comment]
Should we introduce a "built-in" page attribute named `page-noindex` ?
I mean, since we are using Cheerio, it should be relatively easy to check if there's a noindex meta tag but we could also just check if there's a `noindex` attribute on the `page` object:

```js
if (page.attributes.noindex) {
  // exclude this page from indexing
} else {
  // index...
}
```

**Comment by mojavelinux** [comment]
Sounds reasonable to me!
