### ISSUE TITLE
No search-index.js generated

### ISSUE THREAD

**Issue by andraz213** [Mogztter/antora-lunr#18]
I've configured lunr as described in the readme and it doesn't work propperly (I'm running it in Windows).
Lunr should generate _searc-index.js_, but all I get is _search_index.json.gz_. 
Am I doing something wrong?

**Comment by danyill** [comment]
Those changes haven't been released in antora-lunr 0.4. In fact I think @Mogztter only made these changes less than 24 hours ago. If you want to use an unreleased version, clone the repository to the location of your project/antora location (using `npm install` on a clone of this repository).

**Comment by Mogztter** [comment]
If you are using the latest release (0.4) please follow the instruction at: https://github.com/Mogztter/antora-lunr/tree/b46ec8b92490d3c5cb838216a4360f7bc6a4325e

The README on master describes the next (unreleased) version.

**Comment by andraz213** [comment]
This worked! Thank you.

**Comment by Mogztter** [comment]
Cool!
I've also released a new version yesterday 0.5.0 😉

**Comment by andraz213** [comment]
Another thing. I wanted to have a partial word search. I added one line in searchIndex function `text = "*" + text + "*"` and it works. I think that would be a nice feature to have out of the box.

**Comment by Mogztter** [comment]
> Another thing. I wanted to have a partial word search. I added one line in searchIndex function text = "*" + text + "*" and it works. I think that would be a nice feature to have out of the box.

I agree, I'm still not sure if we should do a first a strict search, then a begins with search and then a contains search. Or a begins with or contains search from the start.

@andraz213 Could you please open an issue so we can track this issue/feature ?

Thanks
