### ISSUE TITLE
Add a list of live documentation sites using Antora with Lunr

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/antora-lunr#24]
- https://docs.fauna.com/
- https://documentation.suse.com/external-tree/en-us/suma/4.0
- https://www.uyuni-project.org/uyuni-docs/

Feel free to add a link to your documentation site.

**Comment by abelsromero** [comment]
The Suse link does not work to me.

**Comment by Mogztter** [comment]
@jcayouette can we add Use in this list? Do you have a working link? Thanks 😀

**Comment by Mogztter** [comment]
@abelsromero There was a missing "r", could you confirm that https://opensource.suse.com/doc-susemanager/ is working ?

**Comment by abelsromero** [comment]
It's working now, thanxs!

**Comment by tbugfinder** [comment]
suse link is invalid.

**Comment by Mogztter** [comment]
> suse link is invalid.

URL changed again, it's now: https://documentation.suse.com/external-tree/en-us/suma/4.0

**Comment by tobru** [comment]
We're using it here: https://hub.syn.tools/
