### ISSUE TITLE
If the site URL is set, only use the pathname segment

### ISSUE THREAD

**Issue by mojavelinux** [Mogztter/antora-lunr#27]
If the site URL is set, only prepend the pathname segment (i.e., context path) to the entries instead of the full value. For example, if the site.url value is `https://example.org/docs`, only use `/docs`. If the site URL does not have a pathname, the entries should begin with `/` (but not `//`).

Only using the pathname makes the index portable as the site is promoted across parallel environments (testing, acceptance, production) or hosted via multiple domains (to achieve high availability).

In brief, the domain segment doesn't matter. What matters (for the browser to assemble the correct URL) is the pathname that comes after the domain.

Using the pathname where possible is now standard practice in Antora. Antora will only use the full value of the site.url if an absolute URL is required (such as for the canonical URLs or in sitemap entries).

**Comment by Mogztter** [comment]
@mojavelinux Good idea.
Should we use [Node.js URL module](https://nodejs.org/api/url.html#url_urlobject_pathname) to parse and extract the pathname?

**Comment by mojavelinux** [comment]
Yes and no. No because site.url can now be a pathname only. So you need to account for that. Yes because when you do detect it is not a pathname, use URL to get it. But then make it empty string if it's a `/`.

Here's the logic: https://gitlab.com/antora/antora/blob/master/packages/redirect-producer/lib/produce-redirects.js#L56-63
