### ISSUE TITLE
Mention the dedicated site generator in the README

### ISSUE THREAD

**Issue by fviolette** [Mogztter/antora-lunr#29]
Hello,

Thanks for this work!

After I followed the instructions in the README and started to customise the default site generator, a Google search revealed the [NPM site generator](https://www.npmjs.com/package/antora-site-generator-lunr?activeTab=readme) to me.

This should be mentioned as one, if not the preferred way to test the project.
The setup of some of the least techy users could be messed up with the local customisation.

**Comment by Mogztter** [comment]
Hello François.

The site generator with Lunr included is basically a hard copy of the default site generator.
While it's easier to get started it also has a few drawbacks. 

Having said that I can add a link to this project in the "Generate an index file":

> To generate an index file, you can either use a [custom site generator pipeline that includes Lunr](https://github.com/Mogztter/antora-site-generator-lunr) or modify your current site generator pipeline.

**Comment by fviolette** [comment]
Sounds good, thanks for the addition.

I'll push for more examples in the [site generator section](https://docs.antora.org/antora/2.1/how-antora-works/) in the Antora docs.
