### ISSUE TITLE
Version bump of lunr.js to 2.3.8

### ISSUE THREAD

**Issue by streetster** [Mogztter/antora-lunr#31]
Current version is `2.3.3`, the latest is `2.3.8` which offers some bugfixes around fuzzy matching. Happy to put together a PR for this...

**Comment by Mogztter** [comment]
> Happy to put together a PR for this...

Yes please, feel free to open a pull request, I will gladly merge it.

**Comment by streetster** [comment]
Just seen 
```
Version mismatch when loading serialised index. Current version of lunr '2.3.8' does not match serialized index '2.3.3'
```
in my browser, let me see whats up.

**Comment by Mogztter** [comment]
I think you need to update both the `package.json` and the file in `vendor`: https://github.com/Mogztter/antora-lunr/tree/master/supplemental_ui/js/vendor

In other words, you need to use the exact same version to serialized and deserialized.

**Comment by streetster** [comment]
Yeah I just deleted that comment out of shame after I realised antora was (obviously) using the released version of `antora-lunr` which includes `2.3.3`...

The PR includes changes to the package.json (+package-lock.json) and vendor/lunr.js files :)
