### ISSUE TITLE
Potential improvements to make to the `README`

### ISSUE THREAD

**Issue by myii** [Mogztter/antora-lunr#6]
@Mogztter Thanks, I followed the `README` and got `lunr` integrated on my Antora 2.0 development setup.  There were a few places where I found that the instructions could be clearer (or be updated).

https://github.com/Mogztter/antora-lunr/blob/ead8207ac0e441848ae032c02006b32f240e7c8a/README.adoc#L56

* This is now `site/search_index.json`.

https://github.com/Mogztter/antora-lunr/blob/ead8207ac0e441848ae032c02006b32f240e7c8a/README.adoc#L62-L68

* I got the impression that I should _edit_ the `url`, instead of just _replacing_ it with the one you gave.
    * Meaning, edit it to work from _my_ fork!
* Something like "Use the following URL..." would be clearer.

https://github.com/Mogztter/antora-lunr/blob/ead8207ac0e441848ae032c02006b32f240e7c8a/README.adoc#L70

* I couldn't make any progress when attempting to use a `file://` reference.
* However, using `serve` and setting `url: http://localhost:5000` in `site.yml` worked beautifully.
* From https://docs.antora.org/antora/2.0/playbook/configure-site/#configure-url:
    * > The base URL **should not end with a trailing slash**.

**Comment by Mogztter** [comment]
> Thanks, I followed the README and got lunr integrated on my Antora 2.0 development setup. 

Well done :rocket: 

> This is now site/search_index.json.

Actually it depends on your configuration.
If your configuration is:

```yml
output:
  dir: ./public
```

Then I'm right :wink: 
But I agree we should probably, say "an index file should be created at the root of your output directory". We could go one step further and explain that the output directory is configured in the playbook with the `output.dir` key ?

> Something like "Use the following URL..." would be clearer.

:+1: 

> I couldn't make any progress when attempting to use a file:// reference.

Technically it can work if you disable web security and allow file access from the file protocol. But we should probably rephrase.
Having said that I need to do some testings to see if we can get it work without a local web server (and without running the browser with additional flags).

Please feel free to open a pull request to clarify the README, I will gladly merge your contribution :smile:
