### ISSUE TITLE
Index ignores site.url and always creates relative links

### ISSUE THREAD

**Issue by a-tokar** [Mogztter/antora-lunr#67]
Generated `search-index.js` always contains only relative paths and ignores `site.url` setting in the playbook.

**Comment by Mogztter** [comment]
Hello @a-tokar, it's intended and this change was made to make the index "portable", see https://github.com/Mogztter/antora-lunr/issues/38

If you are using the default UI, please make sure to use the latest version of the `supplemental_ui` directory: https://github.com/Mogztter/antora-lunr/tree/v0.7.1/supplemental_ui

**Comment by a-tokar** [comment]
@Mogztter thanks for the information!
Looks like I used not the most recent version...

**Comment by Mogztter** [comment]
No worries, the update procedure is a bit cumbersome!
