### ISSUE TITLE
How to support other languages?

### ISSUE THREAD

**Issue by jabby** [Mogztter/antora-lunr#73]
Hello @Mogztter 

Thanks for your work on antora-lunr and other projects I used. 

I quickly integrate antora-lunr through antora-site-generator-lunr on my website. https://jabby-techs.fr

As you can see, my website is in french and by default lunr only support english. There are some language plugins available to support french and other languages. See https://lunrjs.com/guides/language_support.html

I would like to know if there is a way to add by some configuration those languages into antora-lunr. The only way I found is to create my own generate-site function but I think it's better to improve this project.

**Comment by Mogztter** [comment]
Hey @jabby 

It's an interesting idea and I never thought about it until now.
As far as I understand, we should require and use the stemmer when indexing documents.
It's not clear if the stemmer also need to be loaded when searching?

Implementation wise, we should probably add a new configuration (i.e. an environment variable named `DOCSEARCH_LANGS` that accepts a comma separated list of langs).

If you want to open a pull request, please feel free to do so 🤗

**Comment by jabby** [comment]
`It's not clear if the stemmer also need to be loaded when searching?` I don't know I will try to create a PR this morning with my tests.
I agree with you, a new environment variable seems the right way to do here. 
If it's empty, I will fallback to english, best way to not break the current behaviour.

**Comment by Mogztter** [comment]
Sounds good, thanks :+1:

**Comment by jabby** [comment]
FYI I found some useful documentation here: https://github.com/MihaiValentin/lunr-languages#indexing-multi-language-content

**Comment by jabby** [comment]
I don't know how to properly test my changes here. Do you have an idea?
Maybe we should verify if the indexation is OK with some tests like the ones from `lunr-languages`?

**Comment by Mogztter** [comment]
> FYI I found some useful documentation here: MihaiValentin/lunr-languages#indexing-multi-language-content

It's not 100% clear if the language stemmer and stopwords list are embedded in the index or if we need to load them when searching (client-side).

> I don't know how to properly test my changes here. Do you have an idea?

You can generate an index with `DOCSEARCH_LANGS` defined as an environment variable, take a look at:

https://github.com/Mogztter/antora-lunr/blob/6c60dc048a6823fbe3abdaa785abf356c3f2ec25/test/test.js#L510-L511

Then you can check that stop words from a language are effectively enabled when doing a search. For instance, you can index "ils jouaient" in French where "ils" is a stop word and the suffix "ent" should be recognized. So if you search "joue" it should find something.
And I believe that if you do the same using the default English stemmer it won't work.

> Maybe we should verify if the indexation is OK with some tests like the ones from lunr-languages?

Yes that's a good idea :+1:

**Comment by jabby** [comment]
I updated my draft PR. Feel free to review and comment my work. 

I'm not sure this part is really good. 
See https://github.com/Mogztter/antora-lunr/pull/74/files#diff-a561630bb56b82342bc66697aee2ad96efddcbc9d150665abd6fb7ecb7c0ab2fR10 and https://github.com/Mogztter/antora-lunr/pull/74/files#diff-a561630bb56b82342bc66697aee2ad96efddcbc9d150665abd6fb7ecb7c0ab2fR273-R274

I also rewrite required part except for the first import. Is it ok for you?

**Comment by Mogztter** [comment]
Thanks @jabby, I will take a look today :eyes:

**Comment by Mogztter** [comment]
resolved in https://github.com/Mogztter/antora-lunr/pull/74
