### ISSUE TITLE
Only index content in within the semantic tag 'article'

### ISSUE THREAD

**Issue by campbellbartlett** [Mogztter/antora-lunr#8]
Should you consider only indexing content in the .doc class?

Take a look at what I've done here: https://github.com/campbellbartlett/antora-lunr/commit/72526c83e181fa20c3eaa8864a1cd7e50d79f246

This prevents things like the header, footer and menu from being indexed, which is present on every page.

**Comment by Mogztter** [comment]
Hello @campbellbartlett 

> Should you consider only indexing content in the .doc class?

Sure, could you please open a pull request ? I will gladly merge it.
Just one nitpick, could you use `article` element instead ? It's more semantic and I think it will be a bit more stable if someone is using this extension with a custom UI.

> This prevents things like the header, footer and menu from being indexed, which is present on every page.

I didn't thought about it, nice catch :+1:

**Comment by campbellbartlett** [comment]
I've opened a PR with this change plus two others in #9

* Only index html with the semantic tag article.
* If the site URL is not set, use a relative URL instead of returning nothing.
* If a title does not have an Id then do not index it, which prevents a Lunr typescript error in browser.

Let me know what you think. Thanks!

**Comment by Mogztter** [comment]
resolved in https://github.com/Mogztter/antora-lunr/pull/9
