### ISSUE TITLE
Gitlab integration

### ISSUE THREAD

**Issue by adarshbm11** [Mogztter/antora-lunr#93]
Hi this is not an issue. Apologies for that.

I got this working locally but I have no idea how to integrate on gitlab.

Could you please have a look and help me?

[Repo](https://gitlab.com/docs-dli/docs-dli.gitlab.io)
[Playbook](https://gitlab.com/docs-dli/docs-dli.gitlab.io/-/blob/master/antora-playbook.yml)
[Pipeline](https://gitlab.com/docs-dli/docs-dli.gitlab.io/-/blob/master/.gitlab-ci.yml)

**Comment by Mogztter** [comment]
Sorry I can't help as I'm not familiar with GitLab CI or the Docker image of Antora (used in your pipeline).

For help with usage, you might try the chat channel. https://gitter.im/antora/users. There are lots of people there who might have knowledge/time to help. I'd like to reserve the issue tracker for tracking changes to the software. Thanks!
